### ISSUE TITLE
这个是繁体中文的，和简体中文还是有很大差

### ISSUE THREAD

**Issue by hotoo** [w3c-html-ig-zh/w3c-glossary#1]
例如

| English | 繁體中文 | 简体中文 |
| --- | --- | --- |
| abstract module | 抽象模組 | 抽象模块 |
| access | 存取、訪問 | 访问 |
| asynchronous | 非同步 | 异步 |
| atomic | 單子 | 原子的 |
| atomic test | 單子測試 | 单元测试 |

等等数不胜数。如果这是简体中文兴趣小组，则应基于这份文档，整理简体中文的对照；如果同时针对繁体和简体中文，则应补充简体部分。

另外，建议文档使用 markdown 等简单的格式维护源文档。

**Comment by othree** [comment]
我以為這裡是中文不分繁簡的興趣小組？

現在裡面的簡體中文是從 w3c hk 以前維護的版本來的，相信已經年久失修了
另外 markdown 的部分可以另外開票

**Comment by amio** [comment]
抱歉不大熟悉繁体中文，“另外开票”是指另开 repo 还是另建一份 md 文件？

另外建议，
也许用个 JSON 或者 yml 格式做数据源生成 html，是否更好？既有良好展现效果，又有文档维护的纯洁性，也不需要担心多处同步问题了。

**Comment by othree** [comment]
抱歉

"票"指的是 github issue，一個 issue 應該針對一個問題就好了
JSON, yml 也屬於另外一個問題，也可以開一個 github issue 來建議
甚至你直接 fork 回去處理過後發 pull request 回來更好

**Comment by amio** [comment]
OK

这种提出新策略的改动会想要得到 owner 认可再动手，毕竟不是修 bug 之类，未必受欢迎呢 :D

**Comment by zqzhang** [comment]
谢谢关注。

中文兴趣小组从本周起开始修订简体中文版词汇表，详见：http://lists.w3.org/Archives/Public/public-html-ig-zh/2014Aug/0013.html

所有的讨论都在兴趣小组邮件组完成，欢迎参加讨论；本人将根据小组讨论结果在每周五更新至此。

**Comment by zqzhang** [comment]
This shall be closed by #6 The Interest Group is reviewing the items week-by-week on mailing list. This review is expected to be finished in few months.
